# Generated by Django 4.1.3 on 2022-12-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-publication_date_and_time']},
        ),
    ]
