# Generated by Django 4.1.3 on 2022-12-07 16:28

import django.core.validators
from django.db import migrations, models
import superstore.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.MinLengthValidator(2), superstore.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('diverse', 'Diverse')], max_length=7),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='profile_picture',
            field=models.URLField(blank=True),
        ),
    ]
