# Generated by Django 4.1.3 on 2022-12-07 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_appuser_first_name_alter_appuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='phone_number',
            field=models.IntegerField(blank=True, default='088888888', validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(15)]),
            preserve_default=False,
        ),
    ]
