# Generated by Django 4.1.3 on 2022-12-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_appuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
