# Generated by Django 4.1.3 on 2022-12-01 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy_name', models.CharField(max_length=25)),
                ('toy_photo', models.ImageField(upload_to='')),
                ('toy_description', models.TextField(max_length=150, validators=[django.core.validators.MinLengthValidator(10)])),
                ('toy_age_restriction', models.PositiveIntegerField()),
                ('toy_price', models.FloatField()),
                ('toy_publication_date', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
