# Generated by Django 4.1.3 on 2022-12-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='toy_name',
            field=models.CharField(max_length=30),
        ),
    ]
